spring.application.name=AAD-Task-IV
spring.datasource.url=jdbc:mysql://localhost:3306/pos_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

